### PR TITLE
wait for service shutdown all the time, not just during restarts

### PR DESCRIPTION
**Pull request by otakup0pe**
Otherwise the init script will return before the service has fully stopped.

### CODE REVIEW

**Comment by portertech** [comment]
I'm going through the open issues related to the `sensu-service` init script, and consolidating the changes https://github.com/sensu/sensu-build/pull/116

**Comment by portertech** [comment]
@rafaelmagu I started w/ your request https://github.com/portertech/sensu-build/commit/548c16926ab86ea6525b2f5548a84deb7a194e74

**Comment by portertech** [comment]
cleaned up pid pgrep.

**Comment by rafaelmagu** [comment]
:+1:

**Comment by portertech** [comment]
Going to close this, as https://github.com/sensu/sensu-build/pull/116 includes this functionality and more.

@otakup0pe Thank you for the PR :+1: 

90cc80c0-7afb-11e4-9130-b5de5f5b2ebf

**Pull request closed without merging**
