### PR TITLE
Add a CentOS 7 Build

### PR DESCRIPTION
**Pull request by benLogN**
This PR adds a Centos 7 build which uses systemd instead of init.d. There's a few pieces to this change:
1. `sensu_configs.rake` no longer includes any files into `/etc/init.d/`
2. Two new recipes (`sensu_init.rake` and `sensu_systemd.rake`) now manage placing the service files.
3. The `Rakefile` now includes different logic based on the init service of the distribution you're building for
4. Systemd init services are used if the build number ends with `.el7`.

I imagine points one through three will be pretty uncontroversial. Using systemd based on build number, though, could be a point of contention. I chose this strategy because baking the EL major version into the release number (`BUILD_NUMBER` in the code) seems to be the standard of the CentOS and EPEL packagers. I'd be happy to take suggestions on another approach for picking which builds should use the systemd configs.

### CODE REVIEW

**Comment by benLogN** [comment]
Created in response to the outstanding question on #89

**Comment by benLogN** [comment]
Bump. Does something need to be changed for this to be merged in?

**Comment by portertech** [comment]
@benLogN I'll give this a good look shortly, as we revisit packaging for Sensu :+1:

**Comment by teotwaki** [comment]
@portertech What's the status of this? Any chance we could get it landed?

**Comment by jrwesolo** [comment]
I'd also love to see this!

**Comment by benLogN** [comment]
Wow, I completely forgot this PR was still out. I'll put in the effort to rebase it if it's likely to get looked at this time...

**Comment by jrwesolo** [comment]
Thanks @benLogN! That would be awesome!

**Comment by benLogN** [comment]
I just rebased this. I wasn't able to test that the 32bit releases were unaffected because the 32bit user on docker hub no longer has centos or debian:squeeze releases.

**Comment by jrwesolo** [comment]
@benLogN Thank you! @portertech What do you think?

**Comment by portertech** [comment]
Does CentOS 7 provide init.d stubs? I have concerns in regards to documentation, consistency between platforms, and consistency between service managers.

**Comment by benLogN** [comment]
CentOS 7 doesn't provide init.d stubs, but they do alias the `service` command to its matching systemd start/stop/restart commands. So `/etc/init.d/sensu-client restart` would no longer work, but `service sensu-client restart` would.

**Comment by jrwesolo** [comment]
@portertech One reason I was hoping for this is because on CentOS 7 the sensu-client service enable does not seem idempotent. Every time I rerun on a client, I get:
````
Notice: /Stage[main]/Sensu::Client::Service/Service[sensu-client]/enable: enable changed 'false' to 'true'
````
When I manually check, it is always set to enabled. It seems that Puppet is having a difficult time detecting that though. I assume it is because we are not using systemd natively. Have you run into this?

**Comment by jrwesolo** [comment]
Opened issue in Puppet module as well for tracking: https://github.com/sensu/sensu-puppet/issues/448

**Comment by jrwesolo** [comment]
@portertech in light of @benLogN's response, what do you need for us to move forward with this? I'll see if I can help out as needed.

**Comment by portertech** [comment]
@jrwesolo I would really like to see init bin stubs, so documentation is still accurate, and it remains easy to help others regardless of the platform release.

**Comment by portertech** [comment]
Also, we need to ensure that init functionality and features are the same across all init strategies, e.g. https://github.com/sensu/sensu-build/pull/148

**Comment by jaxxstorm** [comment]
I'd like to help out here, what's needed to move this forward?

**Comment by cwjohnston** [comment]
We are currently working to migrate Sensu's build and release process away from the tools in this repo to a toolchain using Chef's Omnibus (see #184). 

As part of this process we are planning to drop support for upstart and runit to focus on sysv and systemd as the officially supported service managers (see https://github.com/sensu/sensu-omnibus/issues/34).

I believe these changes will not be necessary for running omnibus builds on Centos 7 and other platforms with systemd as the init system. I've added this PR to the 0.27 milestone to reflect that it is superseded by the switch to omnibus builds which will be used to generate Sensu 0.27 packages.

**Pull request closed without merging**
