### PR TITLE
Update Windows MSI build WinSW

### PR DESCRIPTION
**Pull request by portertech**
- Support .NET v4.0

- Working EventMachine 1.0.9 SSL

- Updated MIT license date

### CODE REVIEW

**Comment by portertech** [comment]
MSI package tests pass on build VM, but it still has .NET 3.5 available. Need to test on fresh VM.

**Comment by cwjohnston** [comment]
2016-03-03 at 6 34 pm
2016-03-03 at 6 36 pm

**Comment by portertech** [comment]
@cwjohnston A think of beauty :+1:

**Comment by portertech** [comment]
Fixed #149

**Pull request merged**
